version: "3"

services:
  ip-bot:
    image: ip-bot:latest
    build:
      context: ./
      args:
        bot_token: ${DISCORD_BOT_SECRET}
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock
