FROM python:alpine
WORKDIR /app

RUN apk add py3-pip

COPY ./requirements.txt ./

COPY ./bot ./bot
COPY ./main.py ./main.py
COPY ./startup/docker-start.sh ./docker-start.sh

VOLUME /etc/khaos-bot/

RUN adduser -S python \
    && mkdir -p "/etc/khaos-bot/plugins" "/etc/khaos-bot/data"\
    && chown python:wheel "/etc/khaos-bot" -R \
    && chown python:wheel "/app" -R \
    && chmod +x ./docker-start.sh

USER python

RUN pip install -r ./requirements.txt

ENTRYPOINT [ "./docker-start.sh" ]