ARG TAG=alpine

FROM python:${TAG}
WORKDIR /app

USER root

ENV PACKAGE_LIST="/etc/khaos-bot/plugins/packages.txt"

COPY ./requirements.txt ./

COPY ./bot ./bot
COPY ./main.py ./main.py
COPY ./startup ./

RUN sh /app/install-pip.sh

VOLUME /etc/khaos-bot/

RUN pip install -r ./requirements.txt

ENTRYPOINT [ "sh", "/app/docker-start.sh" ]