name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build alpine Docker image
      run: docker build . --file Dockerfile --tag deuce109/khaos-bot:alpine --build-arg TAG=alpine
    - name: Build slim Docker image
      run: docker build . --file Dockerfile --tag deuce109/khaos-bot:slim --build-arg TAG=slim
    - name: Build trixie Docker image
      run: docker build . --file Dockerfile --tag deuce109/khaos-bot:trixie --build-arg TAG=trixie
    - name: Build bookworm Docker image
      run: docker build . --file Dockerfile --tag deuce109/khaos-bot:bookworm --build-arg TAG=bookworm
