name: Docker Image CI

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [bookworm, alpine, slim, trixie]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file docker/dockerfile --tag deuce109/khaos-bot:${{ matrix.tag }} --build-arg TAG=${{ matrix.tag }}
        docker tag deuce109/khaos-bot:${{ matrix.tag }} deuce109/khaos-bot:${{ matrix.tag }}-${{ github.event.release.tag_name }}
        docker push deuce109/khaos-bot:${{ matrix.tag }}-${{ github.event.release.tag_name }}
        docker push deuce109/khaos-bot:${{ matrix.tag }}

    - name: Tag and push latest
      if: matrix.tag == 'alpine'
      run: |
        docker tag deuce109/khaos-bot:alpine deuce109/khaos-bot:latest
        docker tag decue109/khaos-bot:alpine deuce109/khaos-bot:${{ github.event.release.tag_name }}
        docker push deuce109/khaos-bot:latest