name: Docker Image Test Build

on:
  push:
    branches: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [bookworm, alpine, slim, trixie]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and push Docker image
      run: |
        docker build . --file docker/dockerfile --tag deuce109/khaos-bot:${{ matrix.tag }} --build-arg TAG=${{ matrix.tag }}